### ISSUE TITLE
More appropriate for personal access token table?

### ISSUE THREAD

**Issue by haron68** [Solomon04/go-docker#2]
https://github.com/Solomon04/go-docker/blob/86af444ea9ac16b99c5bcd89f0ef736498723ff1/database/migrations/mysql/000001_create_users_table.up.sql#L8

Should `oauth_provider` and `oauth_identifier` be in personal access token table?
Why are they in the user table if not a part of personal access token table?

**Comment by Solomon04** [comment]
The `oauth_provider` and `oauth_identifier` are equivalent to a user's password. Look at the users table in production and see how we use the two fields to identitfy the user instead of a password for users that signed up with an oauth provider. The oauth_provider isn't related to a `personal_access_token`
